apiVersion: apps/v1     # apiVersion是当前配置格式的版本
kind: Deployment        # kind是要创建的资源类型，这里是Deploymnet
metadata:               # metadata是该资源的元数据，name是必须的元数据项
  name: test-edge-deployment
  labels:
    app: nginx
spec:                   # spec部分是该Deployment的规则说明
  replicas: 1           # relicas指定副本数量，默认为1
  selector:
    matchLabels:
      app: nginx
  template:             # template定义Pod的模板，这是配置的重要部分
    metadata:           # metadata定义Pod的元数据，至少要顶一个label，label的key和value可以任意指定
      labels:
        app: nginx
    spec:               # spec描述的是Pod的规则，此部分定义pod中每一个容器的属性，name和image是必需的
      nodeSelector:
        kubernetes.io/hostname: edge-zero02
      containers:
      - name: nginx
        image: arm32v6/nginx:alpine-perl
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service           # not available on edge: https://github.com/kubeedge/kubeedge/issues/2083
metadata:
  name: test-edge-service
  labels:
    app: test-edge-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
