apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperature-and-humidity-mapper
  labels:
    app: temperature-and-humidity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temperature-and-humidity
  template:
    metadata:
      labels:
        app: temperature-and-humidity
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: "edge-zero02"
      containers:
      - name: temperature-and-humidity
        image: edge-temperature-and-humidity:v1
        env:
        - name: DHT11PIN
          value: "18"
        - name: DEVICE_NAME   # device name in crds/device.yaml
          value: "temperature-and-humidity"
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true