apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperature-mapper
  labels:
    app: temperature
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temperature
  template:
    metadata:
      labels:
        app: temperature
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: "edge-zero01"
      containers:
      - name: temperature
        image: kubeedge-temperature-mapper:test
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
