apiVersion: devices.kubeedge.io/v1alpha1
kind: Device
metadata:
  name: temperature-and-humidity
  labels:
    description: temperature-and-humidity
spec:
  deviceModelRef:
    name: tmp-rh-model
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: 'kubernetes.io/hostname'
            operator: In
            values:
              - edge-zero02
status:
  twins:
    - propertyName: temperature-status
      desired:
        metadata:
          type: string
        value: ''
    - propertyName: humidity-status
      desired:
        metadata:
          type: string
        value: ''
